kind: pipeline
type: docker
name: default

platform:
  os: linux
  arch: amd64

steps:
- name: Build
  image: golang
  commands:
  - go build .
- name: Discord Notification
  image: appleboy/drone-discord
  settings:
    webhook_id:
      from_secret: WEBHOOK_ID
    webhook_token:
      from_secret: SECRET_ID