on: [push, pull_request]
name: Build

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4]

    - uses: actions/setup-go@v5
      with:
        go-version: '1.24'
        cache-dependency-path: "go.sum"

    - name: Build
      run: go build .