on: [push, pull_request]
name: Build

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Install GoLang
      uses: actions/setup-go@v2
      with:
        go-version: 1.17.x
    - name: Checkout Code
      uses: actions/checkout@v2
    - name: Build
      run: go build .