name: Build

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Install GoLang
      uses: actions/setup-go@v2
      with:
        go-version: 1.17.x
    - name: Checkout Code
      uses: actions/checkout@v2
    - uses: actions/cache@v2
      path: |
        ~/go/pkg/mod
        ~/.cache/go-build
      key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
      restore-keys: ${{ runner.os }}-go-
    - name: Build
      run: go build .